### ISSUE TITLE
NX breaks when processing USSEP files

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.Archives.Nx#9]
Steps for reproduction:

* Install USSEP in the app
* Deploy the loadout
* Get a zStd error (if the NX archive manager was used)

```
00:01:36.815 [ERROR] Unobserved task exception|System.InvalidOperationException: ZStd Decompression error: Operation made no progress over multiple calls, due to output buffer being full
   at NexusMods.Archives.Nx.Utilities.Compression.Decompress(CompressionPreference method, Byte* source, Int32 sourceLength, Byte* destination, Int32 destinationLength)
   at NexusMods.Archives.Nx.Packing.NxUnpacker.ExtractBlock(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
00:02:50.807 [INFO] Finished running C:/Games/GOG Galaxy/Games/Skyrim Anniversary Edition/SkyrimSE.exe
```

**Comment by halgari** [comment]
Example file was added to discord: https://discord.com/channels/1134149061080002713/1134151856537469060/1135706194204426411

**Comment by Sewer56** [comment]
Closing this for now because I want to believe https://github.com/Nexus-Mods/NexusMods.Archives.Nx/pull/13 fixed this.
